// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingListApp.Data;

#nullable disable

namespace ShoppingListApp.Data.Migrations
{
    [DbContext(typeof(ShoppingListContext))]
    [Migration("20230124100923_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShoppingListApp.Domain.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Shops", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Aldi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lidl"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Delhaize"
                        });
                });

            modelBuilder.Entity("ShoppingListApp.Domain.ShoppingList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShoppingLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Week 1"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Week 2"
                        });
                });

            modelBuilder.Entity("ShoppingListApp.Domain.ShoppingListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<int?>("ShopId")
                        .HasColumnType("int");

                    b.Property<int>("ShoppingListId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.HasIndex("ShoppingListId");

                    b.ToTable("ShoppingListItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Index = 0,
                            ShopId = 1,
                            ShoppingListId = 1,
                            Text = "Carrots"
                        },
                        new
                        {
                            Id = 2,
                            Index = 1,
                            ShoppingListId = 1,
                            Text = "Candy"
                        },
                        new
                        {
                            Id = 3,
                            Index = 2,
                            ShopId = 3,
                            ShoppingListId = 1,
                            Text = "Water"
                        },
                        new
                        {
                            Id = 4,
                            Index = 0,
                            ShoppingListId = 2,
                            Text = "Apples"
                        },
                        new
                        {
                            Id = 5,
                            Index = 1,
                            ShopId = 2,
                            ShoppingListId = 2,
                            Text = "Potatoes"
                        },
                        new
                        {
                            Id = 6,
                            Index = 2,
                            ShopId = 2,
                            ShoppingListId = 2,
                            Text = "Chicken"
                        },
                        new
                        {
                            Id = 7,
                            Index = 3,
                            ShopId = 2,
                            ShoppingListId = 2,
                            Text = "Cheese"
                        });
                });

            modelBuilder.Entity("ShoppingListApp.Domain.ShoppingListItem", b =>
                {
                    b.HasOne("ShoppingListApp.Domain.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId");

                    b.HasOne("ShoppingListApp.Domain.ShoppingList", "ShoppingList")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("ShoppingListApp.Domain.ShoppingList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
