// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingListApp.Data;

#nullable disable

namespace ShoppingListApp.Data.Migrations
{
    [DbContext(typeof(ShoppingListContext))]
    partial class ShoppingListContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShoppingListApp.Domain.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Shops", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Aldi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lidl"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Delhaize"
                        });
                });

            modelBuilder.Entity("ShoppingListApp.Domain.ShoppingList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShoppingLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Week 1"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Week 2"
                        });
                });

            modelBuilder.Entity("ShoppingListApp.Domain.ShoppingList", b =>
                {
                    b.OwnsMany("ShoppingListApp.Domain.ShoppingListItem", "Items", b1 =>
                        {
                            b1.Property<int>("ShoppingListId")
                                .HasColumnType("int");

                            b1.Property<int>("Index")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Index"), 1L, 1);

                            b1.Property<int?>("ShopId")
                                .HasColumnType("int");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ShoppingListId", "Index");

                            b1.HasIndex("ShopId");

                            b1.ToTable("ShoppingListItems", (string)null);

                            b1.HasOne("ShoppingListApp.Domain.Shop", "Shop")
                                .WithMany()
                                .HasForeignKey("ShopId");

                            b1.WithOwner("ShoppingList")
                                .HasForeignKey("ShoppingListId");

                            b1.Navigation("Shop");

                            b1.Navigation("ShoppingList");

                            b1.HasData(
                                new
                                {
                                    ShoppingListId = 1,
                                    Index = 1,
                                    ShopId = 1,
                                    Text = "Carrots"
                                },
                                new
                                {
                                    ShoppingListId = 1,
                                    Index = 2,
                                    Text = "Candy"
                                },
                                new
                                {
                                    ShoppingListId = 1,
                                    Index = 3,
                                    ShopId = 3,
                                    Text = "Water"
                                },
                                new
                                {
                                    ShoppingListId = 2,
                                    Index = 1,
                                    Text = "Apples"
                                },
                                new
                                {
                                    ShoppingListId = 2,
                                    Index = 2,
                                    ShopId = 2,
                                    Text = "Potatoes"
                                },
                                new
                                {
                                    ShoppingListId = 2,
                                    Index = 3,
                                    ShopId = 2,
                                    Text = "Chicken"
                                },
                                new
                                {
                                    ShoppingListId = 2,
                                    Index = 4,
                                    ShopId = 2,
                                    Text = "Cheese"
                                });
                        });

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
